---
title: "Data visualisation using ggplot2"
output: html_notebook
---

```{r}
library(magrittr)
library(data.table)
library(ggplot2)

source("../../../Projects/share/source/sequencing-analysis/R/ggplot_theme.R")
```

# Loading and writing data

```{r}
flights <- fread("nycflights13/flights.txt") # Flights that departed from NYC in 2013
weather <- fread("nycflights13/weather.txt") # Weather at each NYC airport for each hour
airports <- fread("nycflights13/airports.txt") # Information on each airport
airlines <- fread("nycflights13/airlines.txt") # Full carrier name from abbreviation
planes <- fread("nycflights13/planes.txt") # Information on each plane

flights <- flights[!is.na(dep_delay)]
```


```{r}

flights.m = flights %>%
  merge(weather) %>%
  merge(planes, by="tailnum") %>%
  merge(airports, by.x = "dest", by.y="faa", all.x=T) %>%
  merge(airlines, by = "carrier")

```

# Simple plot
```{r}
m.delay <- flights.m[, .(mean_delay = mean(dep_delay, na.rm = T)), by = month]

p <- ggplot(m.delay, aes(x = month, y = mean_delay))

p + geom_col() +
  ggsave("figures/simple_plot_bars.pdf", width=4, height=2)

p + geom_line() +
  ggsave("figures/simple_plot_line.pdf", width=4, height=2)

p +  geom_point() +
  ggsave("figures/simple_plot_point.pdf", width=3, height=2)

p +  geom_col()+
  geom_point() +
  geom_line() +
  ggsave("figures/simple_plot_all.pdf", width=4, height=2)

ggplot(flights.m, aes(x = carrier, y = log(dep_delay))) +
  geom_boxplot() +
  ggsave("figures/simple_plot_boxplot.pdf", width=4, height=2)


ggplot(flights.m, aes(x = carrier, y = log(dep_delay))) +
  geom_violin() +
  ggsave("figures/simple_plot_violin.pdf", width=4, height=2)


```

# Asthetic mappings

```{r}
library(maps)

flights.m[carrier %in% c("UA", "DL", "AA") ,.(mean_delay =  mean(dep_delay)), by=.(month, origin, carrier)] %>%
  ggplot(aes(x=month, y=mean_delay, colour = origin, linetype = carrier)) +
  geom_line() +
  ggsave("figures/aesthetics_lines.pdf", width = 6, height=3)

ggplot(flights.m, aes(x=carrier, y=log10(dep_delay), fill=origin))+
  geom_boxplot() +
  ggsave("figures/scales.pdf", width=6, height=2)

ggplot(unique(flights.m, by="dest"), aes(x=lon,y=lat, label=dest, colour=origin)) + 
  geom_text() +
  ggsave("figures/aesthetics_lines.pdf", width = 6, height=3)

```
# Facets
```{r}
ggplot(flights.m[carrier %in% c("UA","AA","DL")], aes(x=factor(hour), y=log10(dep_delay), fill=origin))+
  facet_wrap(~carrier)+
  geom_boxplot()+
  ggsave("figures/facets.pdf", width=12, height=3)


ggplot(flights.m[carrier %in% c("UA","AA","DL")], aes(x=factor(hour), y=log10(dep_delay), fill=origin))+
  facet_grid(origin~carrier)+
  geom_boxplot()+
  ggsave("figures/facet_grid.pdf", width=12, height=5)
```

# Computations on data
```{r}
ggplot(flights.m, aes(x=humid, y=dep_delay, colour=origin, fill=origin))+
  stat_summary_bin(fun.y = mean, na.rm=T, geom="line")+
  stat_summary_bin(fun.data = mean_cl_boot, geom="ribbon", alpha=0.2, colour=NA)+
  ggsave("figures/computations_on_data.pdf", width=5, height=3)

ggplot(flights.m, aes(x=hour, y=dep_delay, colour=origin, fill=origin))+
  stat_summary(fun.y = mean, na.rm=T, geom="line")+
  stat_summary(fun.data = mean_cl_boot, geom="ribbon", alpha=0.2, colour=NA) +
  ggsave("figures/computations_on_data_lines.pdf", width =4, height=2)


ggplot(flights.m, aes(x=temp, y=dep_delay, colour=origin, fill=origin))+
  stat_summary_bin(fun.y = mean, na.rm=T, geom="line")+
  stat_summary_bin(fun.data = mean_cl_boot, geom="ribbon", alpha=0.2, colour=NA)+
  ggsave("figures/computations_on_data_temp.pdf", width=4, height=2)


ggplot(flights.m, aes(x=seats, y=log(dep_delay), colour=origin))+
  stat_summary(aes(colour=factor(origin)), fun.y = mean, na.rm=T, geom="line")
```

# Geometric objects - one variable

```{r}

ggplot(flights.m, aes(x=dep_delay-arr_delay))+
  geom_histogram() +
  ggsave("figures/geometric_objects_one_continuous_variable_hist.png", width=4, height=3)

```
# Geometric objects - two variables

```{r}
ggplot(flights.m, aes(x = dep_delay, y=arr_delay))+
  geom_point()+
  ggsave("figures/geometric_objects_two_continuous_variables.png", width=4, height=3)
```

```{r}
ggplot(flights.m, aes(x = dep_delay, y=arr_delay))+
  geom_hex()+
  ggsave("figures/geometric_objects_two_continuous_variables_density.png", width=4, height=3)
```
```{r}
ggplot(flights.m, aes(x = origin, y=distance))+
  geom_boxplot()+
    ggsave("figures/geometric_objects_two_variables_boxplot.png", width=4, height=3)

```

# Geometric objects - three variables

```{r}
flights.m[carrier %in% c("UA","DL","AA"),.(mean_delay = mean(dep_delay)), by=.(month, hour, origin)] %>%
ggplot(aes(x = month, y= hour, fill = mean_delay))+
  facet_grid(~origin) +
  geom_tile()+
  scale_fill_viridis_c()+
  ggsave("figures/geometric_objects_three_variables_raster.png", width=9, height=3)

flights.m[carrier %in% c("UA","DL","AA"),.(n_flights = .N) ,by=.(month, hour, origin)] %>%
ggplot(aes(x = month, y= hour, fill = n_flights))+
  facet_grid(~origin) +
  geom_tile()+
  scale_fill_viridis_c()+
  ggsave("figures/geometric_objects_three_variables_raster_nflights.png", width=9, height=3)
```



# Scales

```{r}
ggplot(flights.m, aes(x=carrier, y=log(dep_delay), fill=origin))+
  geom_boxplot() +
  scale_fill_grey() +
  ggsave("figures/scales_grey.pdf", width=6, height=2) ->p
 
ggplot(flights.m, aes(x=carrier, y=log(dep_delay), fill=origin))+
  geom_boxplot() +
  scale_fill_brewer() +
  ggsave("figures/scales_brewer.pdf", width=6, height=2)

ggplot(flights.m, aes(x=carrier, y=log(dep_delay), fill=origin))+
  geom_boxplot() +
  scale_fill_manual( values = c("black","grey","white")) +
  ggsave("figures/scales_grey.pdf", width=6, height=2)

```
#Coordinate transformation

```{r}

ggplot(flights.m, aes(x = wind_dir, y=dep_delay))+
  stat_summary_bin(fun.y=mean, geom="bar")+ 
  ggsave("figures/coord_trans_none.pdf", width=3, height=3)


ggplot(flights.m, aes(x = wind_dir, y=dep_delay))+
  stat_summary_bin(fun.y=mean, geom="bar") +
  coord_polar()+
  ggsave("figures/coord_trans_polar.pdf", width=3, height=3)


ggplot(flights.m, aes(x = wind_dir, y=dep_delay, fill=origin))+
  stat_summary_bin(fun.y=mean, geom="bar", position ="dodge") +
  coord_polar()+
  ggsave("figures/coord_trans_polar_fill.pdf", width=5, height=3)

ggplot(flights.m, aes(x = wind_dir, y=dep_delay, fill=origin))+
  stat_summary_bin(fun.y=mean, geom="bar", position ="dodge") +
  coord_polar()+
  ggsave("figures/coord_trans_polar_fill_dodge.pdf", width=5, height=3)

```
# Smoothening

```{r}

ggplot(flights.m, aes(x=month, y=seats, colour=origin)) +
  stat_summary(fun.y = mean, geom = "point")+
  stat_smooth(method="lm") +
  ggsave("figures/smoothening_lm.pdf", width=5, height=3)

ggplot(flights.m, aes(x = hour, y = dep_delay, group=month, colour = month %in% c(6,7))) +
  stat_summary(fun.y = mean, geom = "point")+
  stat_smooth() +
  ggsave("figures/smoothening.pdf", width=6, height=3)

```
# Labels
```{r}
flights.m[carrier %in% c("UA", "DL", "AA") ,.(mean_delay =  mean(dep_delay)), by=.(month, origin, carrier)] %>%
  ggplot(aes(x=month, y=mean_delay, colour = origin, linetype = carrier)) +
  geom_line() +
  labs(x= "Month", y="Avg. delay (min)", colour = "Airport", linetype = "Airline", title = "Summer craze")+
  ggsave("figures/labels_lines.pdf", width = 6, height=3.2)
```

# Position adjustments

```{r}
p <- flights.m[carrier %in% c("UA", "DL", "AA") ,.(mean_delay =  mean(dep_delay)), by=.(month, origin, carrier)] %>%
  ggplot(aes(x=month, y=mean_delay, fill = origin, alpha = carrier))


p + geom_col(position = "stack") + ggsave("figures/position_stack.pdf", width = 7, height=2.5)
p + geom_col(position = "dodge") + ggsave("figures/position_dodge.pdf", width = 7, height=2.5)
p + geom_col(position = "fill") + ggsave("figures/position_fill.pdf", width = 7, height=2.5)
```